---
title: Spatial visualisations
output: 
  html_document: 
    toc: true
    toc_float: true
    number_sections: yes
    code_folding: hide
---

```{r setup, include = F}
library(knitr)
knitr::opts_chunk$set(list(echo=TRUE,
                           eval=TRUE,
                           cache=TRUE,
                           warning=FALSE,
                           message=FALSE))
opts_chunk$set(fig.width = 10, fig.height = 10)
library(ggplot2)
library(dplyr)
options(scipen=999)

d <- readRDS("./data/sdmr15.RDS")
meta <- readRDS("./data/meta_df.RDS")

label_data <- function(data=d, variable="tvtot", metadata=meta, into.factor=TRUE){
  if (!"factor" %in% unique(metadata[metadata$code %in% variable,]$class)) stop("Variable is either character or numeric and has no labels")
  vardata <- metadata[metadata$code %in% variable,]
  new_values <- with(vardata, label[match(data[[variable]], value)])
  if (into.factor) new_values <- factor(new_values, levels=vardata$label)
  return(new_values)
}

```

# Sites of interview

## Whole Russia

```{r draawmap, fig.height=10}
load("./data/archive/location_df.RData")

library(dplyr)

d$PUNKTc1_lab <- label_data(data = d, variable = "PUNKTc1")

n_cases <- d %>% group_by(PUNKTc1_lab) %>%
  summarise(n = n()) %>%
  filter(!grepl("[0-9]",PUNKTc1_lab)) %>% 
  rename(PUNKTc1 = PUNKTc1_lab)

# 
# location_df <- merge(location_df,n_cases,by.x="PUNKTc1",by.y="PUNKTc1_lab")

library(rgdal)

shape <- readOGR(dsn = "/home/aurelius/btsync/mk/data/shapefiles/russia/naturalearthdata/mod",
                 layer = "ADM_federal_district", stringsAsFactors=FALSE)


library(ggplot2)
library(maptools)
library(rgeos)
shape <- spTransform(shape, CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
shape$id <- rownames(shape@data)
map.points <- fortify(shape, region = "id")
map.df <- merge(map.points, shape, by = "id")


t <- ggplot(data = map.df, aes(long,lat,group=group))
t <- t + geom_polygon(fill = "grey80", colour = alpha("white", 1/2), size = 0.2, show.legend = F)
t <- t + geom_point(data=location_df, aes(lon, lat, group=PUNKTc1, size=n),shape=1,alpha=.4) 
t <- t + geom_text(data=location_df, aes(lon, lat, label = n,group = PUNKTc1), size=2,vjust=-1)
t <- t + theme_minimal() + 
  theme(panel.grid  = element_blank()) +
  theme(legend.position = "top") + 
  theme(text = element_text(family = "Open Sans", size= 9)) +
  theme(axis.text= element_blank()) +
  theme(axis.title = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(legend.text= element_text(size = 8)) +
  theme(legend.title= element_text(size = 8)) +
  scale_fill_manual(values=c(mapscale[4],mapscale[2]))
t <- t + theme(legend.position=c(.5, .9))
t <- t + coord_map(project="orthographic",
                   xlim = c(15,190), ylim = c(45,55))
t <- t + theme(legend.key.size = unit(.4, "cm"))
p1 <- t + theme(text = element_text(family="Open Sans"))
p1

```



```{r feddists, results="asis"}

shape_o <- readOGR(dsn = "/home/aurelius/btsync/mk/data/shapefiles/russia/naturalearthdata/mod",
                 layer = "ADM_federal_district", stringsAsFactors=FALSE)

for (fd in unique(shape_o$eng)){
  
  
  shape <- shape_o[shape_o$eng %in% fd,]
  shape <- spTransform(shape, CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
  dx <- data.frame()
  for (i in 1:nrow(location_df)){
    
  point <- location_df[i,2:3]
  sp2   <- SpatialPoints(point,proj4string=CRS(proj4string(shape)))
  cont <- gContains(shape,sp2)
  if (!cont) next()
  if (cont){
    newrow <- data.frame(c(location_df$PUNKTc1[i],point))
    names(newrow)[1] <- "PUNKTc1"
    dx <- rbind(dx,newrow)
  } 
  }
  if (nrow(dx) >= 1){
    dx <- merge(dx,n_cases,by="PUNKTc1")
  } else next()
  
  shape$id <- rownames(shape@data)
  map.points <- fortify(shape, region = "id")
  map.df <- merge(map.points, shape, by = "id")
  
  cat("\n\n")
  cat(paste("##",fd))
  cat("\n\n")
  
  t <- ggplot(data = map.df, aes(long,lat,group=group))
  t <- t + geom_polygon(fill = "grey80", colour = alpha("white", 1/2), size = 0.2, show.legend = F)
  t <- t + geom_point(data=dx, 
                      aes(lon, lat, group=PUNKTc1, size=n),shape=1,alpha=.4)
  t <- t + geom_text(data=dx ,
                     aes(lon, lat, label = n,group = PUNKTc1), size=2,vjust=-1)
  t <- t + ggrepel::geom_text_repel(data=dx,
                        aes(lon, lat, 
                            label = gsub('(.{1,10})(\\s|$)', '\\1\n', PUNKTc1),
                            group = PUNKTc1), size=2.5,lineheight=.7)
  t <- t + theme_minimal() + 
    theme(panel.grid  = element_blank()) +
    theme(legend.position = "top") + 
    theme(text = element_text(family = "Open Sans", size= 9)) +
    theme(axis.text= element_blank()) +
    theme(axis.title = element_blank()) +
    theme(axis.ticks = element_blank()) +
    theme(legend.text= element_text(size = 8)) +
    theme(legend.title= element_text(size = 8)) +
    scale_fill_manual(values=c(mapscale[4],mapscale[2]))
  t <- t + theme(legend.position=c(.5, .9))
  t <- t + coord_map(project="orthographic")
  t <- t + theme(legend.key.size = unit(.4, "cm"))
  t <- t + labs(title=fd)
  p1 <- t + theme(text = element_text(family="Open Sans"))
  print(p1)
}




```

