---
title: Descriptive trust analysis
output: 
  html_document: 
    toc: true
    toc_float: true
    number_sections: yes
    code_folding: hide
---


```{r setup, include = F}
library(knitr)
knitr::opts_chunk$set(list(echo=TRUE,
                           eval=FALSE,
                           cache=TRUE,
                           warning=FALSE,
                           message=FALSE))
opts_chunk$set(fig.width = 10, fig.height = 6)
library(ggplot2)
library(dplyr)
options(scipen=999)

# if (!file.exists("./data/d_merge_L_class.RData")) source("./lataa_datat.R")
# load("./data/merged_4wave20151110N.RData")
# longi <- d_merge_N
# load("./data/d_merge_N_class.RData")
# longi_class <- d_merge_N_class
# load("./data/sdmr_4_english_language_versionN.RData")
# cross15 <- d15n
# dd <- cross15
dd <- readRDS("./data/sdmr15.RDS")

source("./code/label_data.R")
```

# Cross-sectional 2015

## Institutional trust


```{r trust, results="asis",  fig.height=10}

# load("./data/label_data.RData")
label_data <- readRDS("./data/label_data.RDS")

trust_vars <- label_data[grepl("Trust:", label_data$name),]
trust_vars <- trust_vars[!duplicated(trust_vars$code),]

# for the tot data.frame
aggdf <- data.frame()

for (i in trust_vars$code){

  dd$trust1 <- label_sdmr(data = dd, var= i)

  tbl <- as.data.frame(prop.table(table(dd$trust1))*100)
  tbl$Freq <- round(tbl$Freq,1)
  tbl$var <- label_data[label_data$code %in% i,"name"]
  aggdf <- rbind(aggdf,tbl)

}

```

## By institution

```{r insttrust, fig.height=10}
tbl <- aggdf
p <- ggplot(data=tbl,# data 
          aes(x=Var1, # x-akselin luokitteleva muuttuja
              y=Freq,
              label=Freq)) # y-akselin jatkuva muuttuja
p <- p + geom_bar(stat="identity", position="dodge")
p <- p + geom_text(position=position_dodge(width=1), vjust=1.5,color="white",size=3)
p <- p + guides(fill = guide_legend(reverse=TRUE))
p <- p + theme(axis.text.x = element_text(angle=90))
p <- p + facet_wrap(~var)
print(p)

```


## By level of trust


```{r insttrust2}
levelit <- tbl %>% filter(Var1 %in% "Fully trust") %>% 
  arrange(-Freq) %>% 
  select(var)

tbl$var <- factor(tbl$var, levels=levelit$var)

p <- ggplot(data=tbl,# data 
          aes(x=var, # x-akselin luokitteleva muuttuja
              y=Freq,
              label=Freq)) # y-akselin jatkuva muuttuja
p <- p + geom_bar(stat="identity", position="dodge")
p <- p + geom_text(position=position_dodge(width=1), vjust=1.5,color="white",size=2)
p <- p + guides(fill = guide_legend(reverse=TRUE))
p <- p + theme(axis.text.x = element_text(angle=90))
p <- p + facet_wrap(~Var1)
print(p)
```

# Trust (institutional and general) by background variables 


```{r subjpov3, results="asis"}

bg_vars <- read.table(textConnection('

name code
"Age"  age
"Sex"  V112c1
"Education" V10c1
"Type of Settlement" V1c1
"General trust" V96c1
"Subjective poverty" V82c1

'), stringsAsFactors=FALSE, header=TRUE)

# lets add the institutional trust
load("./data/label_data.RData")
trust_vars <- label_data[grepl("Trust", label_data$name),]
trust_vars <- trust_vars[!duplicated(trust_vars$code),c("name","code")]

for (tr in trust_vars$code){
  
  dd$indep <- label_sdmr(dd,tr, factor=TRUE)
  
  cat("\n\n")
  cat(paste("##",trust_vars[trust_vars$code %in% tr,]$name),"-",tr)
  cat("\n\n")
  
  for (i in bg_vars$code){
  
  if (i %in% "age"){
  dd$depend[dd[[i]] < 20] <- "Below 20"
  dd$depend[dd[[i]] >= 20 & dd$age < 30] <- "20-29"
  dd$depend[dd[[i]] >= 30 & dd$age < 40] <- "30-39"
  dd$depend[dd[[i]] >= 40 & dd$age < 50] <- "40-49"
  dd$depend[dd[[i]] >= 50 & dd$age < 60] <- "50-59"
  dd$depend[dd[[i]] >= 60 & dd$age < 70] <- "60-69"
  dd$depend[dd[[i]] >= 70] <- "70 and older"
  
  dd$depend <- factor(dd$depend, 
                      levels=c(c("Below 20",
                                 "20-29",
                                 "30-39",
                                 "40-49",
                                 "50-59",
                                 "60-69",
                                 "70 and older")))
  } else dd$depend <- label_sdmr(dd,i, factor=TRUE)
  
  tbl <- as.data.frame(prop.table(table(dd$indep,dd$depend),2)*100)
  
  levels(tbl$Var1) <- gsub('(.{1,20})(\\s|$)', '\\1\n', levels(tbl$Var1))
  levels(tbl$Var2) <- gsub('(.{1,20})(\\s|$)', '\\1\n', levels(tbl$Var2))
  
  cat("\n\n")
  cat(paste("###",bg_vars[bg_vars$code %in% i,]$name),"-",i)
  cat("\n\n")
  
  p <- ggplot(data=tbl,# data 
              aes(x=Var2, # x-akselin luokitteleva muuttuja
                  y=Freq,
                  fill=Var1)) # y-akselin jatkuva muuttuja
  p <- p + geom_bar(stat="identity")
  p <- p + guides(fill = guide_legend(reverse=TRUE, title = trust_vars[trust_vars$code %in% tr,]$name))
  p <- p + labs(title=paste(trust_vars[trust_vars$code %in% tr,]$name, "- share of respondents - ", bg_vars[bg_vars$code %in% i, "name"]),
                x=bg_vars[bg_vars$code %in% i,]$name)
  p <- p + theme(axis.text.x = element_text(angle=90))
  print(p)
  
  tbl <- as.data.frame(table(dd$indep,dd$depend))
  
  levels(tbl$Var1) <- gsub('(.{1,20})(\\s|$)', '\\1\n', levels(tbl$Var1))
  levels(tbl$Var2) <- gsub('(.{1,20})(\\s|$)', '\\1\n', levels(tbl$Var2))
  
  tbl$Freq <- round(tbl$Freq, 1)
  
  p <- ggplot(data=tbl,# data 
              aes(x=Var1, # x-akselin luokitteleva muuttuja
                  y=Var2,
                  fill=Freq,
                  label=Freq)) # y-akselin jatkuva muuttuja
  p <- p + geom_tile()
  p <- p + geom_text(color="white")
  p <- p + labs(y=bg_vars[bg_vars$code %in% i,]$name,
                x=trust_vars[trust_vars$code %in% tr,]$name)
  p <- p + labs(title=paste(trust_vars[trust_vars$code %in% tr,]$name, "- nr of cases per cell - ", bg_vars[bg_vars$code %in% i, "name"]))
  print(p)

}
}





```





# Merged data

```{r load_merged_data}

```


## Class variables

```{r, eval=FALSE}
l <- d_merge_N_class


l %>% # data
  # muokataan muuttujia
  mutate(income = as.integer(v74_1998_2007_2015),
         age = 2015 - v111_1991_1998_2007_2015) %>% 
  # ryhmitellään data
  group_by(occup_groups_labelled) %>% 
  # lasketaan ryhmille tunnuslukuja tuloista ja iästä
  summarise(keskiarvo_ika = mean(age, na.rm=TRUE),
            mediaani_ika = median(age, na.rm=TRUE),
            keskihajonta_ika = sd(age,na.rm = TRUE),
            # tulot,
            keskiarvo_tulot = mean(income, na.rm=TRUE),
            mediaani_tulot = median(income, na.rm=TRUE),
            keskihajonta_tulot = sd(income,na.rm = TRUE)
  ) %>% knitr::kable() #%>% View()


l %>% # data
  # muokataan muuttujia
  mutate(income = as.integer(v74_1998_2007_2015),
         age = 2015 - v111_1991_1998_2007_2015) %>% 
  # ryhmitellään data
  group_by(autonomia_labelled) %>% 
  # lasketaan ryhmille tunnuslukuja tuloista ja iästä
  summarise(keskiarvo_ika = mean(age, na.rm=TRUE),
            mediaani_ika = median(age, na.rm=TRUE),
            keskihajonta_ika = sd(age,na.rm = TRUE),
            # tulot,
            keskiarvo_tulot = mean(income, na.rm=TRUE),
            mediaani_tulot = median(income, na.rm=TRUE),
            keskihajonta_tulot = sd(income,na.rm = TRUE)
  ) %>% knitr::kable() #%>%  View()


#' # Tulot
#' 
d <- d15l
d$tulot <- as.integer(d$V74c1) / 10404

p <- ggplot(data=d,# data 
            aes(x=as.integer(V74c1), # x-akselin luokitteleva muuttuja
                color=V112c1)) # y-akselin jatkuva muuttuja
p <- p + geom_density()
p


p <- ggplot(data=d,# data 
            aes(x=as.integer(tulot), # x-akselin luokitteleva muuttuja
                color=V112c1)) # y-akselin jatkuva muuttuja
p <- p + geom_density()
p
```



