---
title: Codebook 2015 data
output: 
  html_document: 
    toc: true
    toc_float: true
    number_sections: yes
    code_folding: hide
---


```{r setup, include = F}
library(knitr)
knitr::opts_chunk$set(list(echo=TRUE,
                           eval=TRUE,
                           cache=FALSE,
                           warning=FALSE,
                           message=FALSE))
opts_chunk$set(fig.width = 10, fig.height = 10)
library(ggplot2)
library(dplyr)
```


**Variables names, codes, values & labels**

<div class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>READ THIS!</strong> If variable has more than 450 values (is numeric in most cases), table only shows first 10 rows!
</div>


```{r taulukot, cache=FALSE, results="asis", eval=TRUE}
library(dplyr)
library(ggplot2)

meta <- readRDS("./data/meta_df.RDS")

for (ind in unique(meta$code)){
  
  code <- ind
  name <- meta[meta$code %in% ind,]$name[1]
  cat("\n\n")
  cat(paste("#",code,"-",name))
  cat("\n\n")
  
  df <- meta[meta$code %in% ind,]
  
  if (nrow(df) >= 450){
   print(knitr::kable(df[1:10,], "html", table.attr='class="table table-striped table-hover"')) 
  } else {
    print(knitr::kable(df, "html", table.attr='class="table table-striped table-hover"'))
  }
 cat("\n\n")

  
}
```


